# Generated by Django 4.1 on 2022-08-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appGH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
                ('especialidade', models.CharField(max_length=3, verbose_name='Especialidade')),
                ('teleconsulta', models.BooleanField(default=False, verbose_name='É teleconsulta?')),
                ('medico_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='appGH.medico', verbose_name='Médico')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='appGH.paciente', verbose_name='Paciente')),
                ('secretario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='appGH.secretario', verbose_name='Secretário')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ('-data_hora', 'paciente_id__usuario_id__first_name'),
            },
        ),
    ]
