# Generated by Django 4.1 on 2022-11-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCalendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='especialidade',
            field=models.CharField(choices=[('CM', 'Clínica Médica'), ('CC', 'Clínica Cirúrgica'), ('CG', 'Clínica Gineco-obstétrica'), ('CP', 'Clínica Pediátrica')], max_length=3, verbose_name='Especialidade'),
        ),
    ]
