# Generated by Django 4.1 on 2022-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('patient', 'Paciente'), ('doctor', 'Médico'), ('secretary', 'Secretário'), ('admin', 'Administrador')], max_length=10, null=True, verbose_name='Tipo de usuário'),
        ),
    ]
