# Generated by Django 4.1 on 2022-10-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGH', '0002_alter_usuario_data_nascimento_alter_usuario_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registro profissional'),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de admissão'),
        ),
    ]
